name: Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
      - run: npm install
      
      - uses: raulanatol/jest-coverage-comment-action@main
        with:
            github-token: ${{ secrets.ACTION_TOKEN }}
            jest-command: 'npm test'