name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: install
        run: npm install

      - uses: ziishaned/jest-reporter-action@v0.0.1
        with:
          github-token: ${{ secrets.ACTION_TOKEN }}
          test-command: "npm test"